### ISSUE TITLE
Visual Studio crash

### ISSUE THREAD

**Issue by AndreyAndreev** [lkytal/SmoothScroll#10]
Exception details:

> System.ObjectDisposedException was unhandled
> Message: An unhandled exception of type 'System.ObjectDisposedException' occurred in mscorlib.dll
> Additional information: Cannot access a disposed object.

Call stask:
>	mscorlib.dll!System.Threading.TimerQueueTimer.Change(uint dueTime, uint period)
> 	mscorlib.dll!System.Threading.Timer.Change(int dueTime, int period)
> 	SmoothScroll.dll!SmoothScroll.ScrollController.~ScrollController()

I wrote a comment about possible fix: https://github.com/lkytal/SmoothScroll/commit/e53679a95964248f3c365f45a14e320d6c214d5a#commitcomment-20832459

**Comment by lkytal** [comment]
Thanks for your feedback. I've removed improper dispose in destructor.
