### ISSUE TITLE
unable to scroll when the cursor is on the "Text" property.

### ISSUE THREAD

**Issue by zer09** [lkytal/SmoothScroll#11]
You cant scroll if the cursor is on the Control Text property, then clicking anywhere on the code, it will suddenly jump.

thanks

vs2015
SmoothScroll 1.0
this is on c# code

**Comment by lkytal** [comment]
Hi, I'm not very clear about the situation you mentioned, like which part do you indicate by "Control Text property"? Some code examples or screenshots will help.

**Comment by zer09** [comment]
I mean fore example on a TextBox, the text property of it.
`txt_box_1.Text = string.Empty`

When you put your cursor on the "Text", then try to scroll, but it wont scroll.

**Comment by lkytal** [comment]
I can't reproduce this problem currently, maybe it's caused by anothor extension, please check out.

**Comment by zer09** [comment]
sorry, I think my problem is on my VS because I already disabled all the extension, it wont freeze but I got a very high cpu when the cursor is the "Text" word.
