### ISSUE TITLE
Precision Touchpad - Decoupled behaviour

### ISSUE THREAD

**Issue by jwefers** [lkytal/SmoothScroll#12]
In general, the behaviour feels decoupled from the trackpad, if you can, compare it with Scrolling in Edge using a Surface Book / Pro 4 (or hopefully a MS-approved precision touchpad), or any MacBook.

When i scroll on my Surface Book, there is a maximum acceleration happening in vs, leading to a distinct lag between what i do at the trackpad and what happens in the window. Also, when i suddenly stop with my fingers, scrolling does not stop but takes about two seconds decelerate (as if i just lifted my fingers). Also, when i initiate scrolling, lift my fingers off and put them back on, scrolling again does not stop.

If this would be doable, imitating OSX/Edge, it'd feel wunderful.

**Comment by lkytal** [comment]
VS provided limited method to react with touchpad programmatically, so I may not be able to address this problem swiftly, but I may come up with some solutions in recents.

**Comment by LiLejia** [comment]
Yes, what really matter is the sample rate of the trackpad which trigger the refresh but not the animation fps actually.
