### ISSUE TITLE
Disable smooth scrolling for Shift + Scroll

### ISSUE THREAD

**Issue by garyng** [lkytal/SmoothScroll#13]
Anyway to support horizontal scrolling without the _smooth_ part?
It seems like this is the only extension that support horizontal scrolling for Visual Studio 2017 though...

**Comment by lkytal** [comment]
You can disable smooth part in the setting

**Comment by garyng** [comment]
But that won't disable smooth scrolling for horizontal scrolling.

**Comment by lkytal** [comment]
Fixed in version 2.8.3.
