### ISSUE TITLE
Visual Studio 2019 depreciated API warning

### ISSUE THREAD

**Issue by dotnetshadow** [lkytal/SmoothScroll#19]
Firstly a great extension,

Just wondering if you are aware of the following issue on Visual Studio 2019 RC

![image](https://user-images.githubusercontent.com/296247/53636158-57981100-3c73-11e9-83fc-b65936df6714.png)

https://docs.microsoft.com/en-us/visualstudio/extensibility/synchronously-autoloaded-extensions?view=vs-2017

**Comment by dotnetshadow** [comment]
Any progress on this?

**Comment by AlohaWorld** [comment]
Tested on Visual Studio 2019 16.0.0 (released on Apr. 2), The issue exists.

**Comment by DJLink** [comment]
I was looking into this just now, it appears the new API requires the extension to target VS2015+, so Smooth Scroll would have to drop support for 2013. Not sure if this would be acceptable. 

Here's an example of the code change required. I might try this myself later to see if it actually work.s

https://github.com/Microsoft/VSSDK-Extensibility-Samples/tree/master/AsyncPackageMigration

**Comment by dotnetshadow** [comment]
@DJLink It will be interesting to see if that works. Perhaps you can create a fork?

**Comment by lkytal** [comment]
Hi, due to limited time I have in recent, I may come back to update this in May.

**Comment by lkytal** [comment]
I've updated version 3.0.0, let me know whether it works as expected or not.

**Comment by dotnetshadow** [comment]
Will install now and let you know

**Comment by DJLink** [comment]
Working ok here too, no warnings, thank you for this.
