### ISSUE TITLE
Text Editor Background Images Bounce when Scrolling

### ISSUE THREAD

**Issue by stricq** [lkytal/SmoothScroll#2]
If you have a background image in the text editor, the image will bounce up and down during smooth scrolling.  (I use KyuuBackground but there are others.)

**Comment by lkytal** [comment]
Only silent trembling were found on my visual Studio.

You may try colorfullIDE extention instend of KyuuBackground, which may address this problem
https://visualstudiogallery.msdn.microsoft.com/fec6375d-f838-4366-b21a-6fccb67205c5
