### ISSUE TITLE
VS2019: SmoothScroll settings freeze VS and crash it

### ISSUE THREAD

**Issue by penCsharpener** [lkytal/SmoothScroll#21]
I really like the shift scroll feature of this extensions but I always turn off the smooth scolling. After the update to version 3.0 I can't access the SmoothScroll settings anymore. 

* I use VS 2019 latest update (16.0.3) but also happens in 16.1 preview 3
* open VS settings
* click on SmoothScroll
* VS freezes and crashes shortly after

as a work around until this is fixed where can I turn off smooth scroll in a settings file?

**Comment by penCsharpener** [comment]
ok I found the settings registry here `%localappdata%\Microsoft\VisualStudio\16.0_<id>`, loaded it with regedit and the setting for smoothscroll was deactivated. So it seems that in the current state the settings aren't even read properly. For the moment I will have to deinstall the extension as I'm not a fan of the buttery smooth scrolling.

**Comment by lkytal** [comment]
Any detailed error logs?

**Comment by lkytal** [comment]
please update to v3.1.0

**Comment by penCsharpener** [comment]
For the future where do I find the error logs?

**Comment by penCsharpener** [comment]
Tried to install
1) it says in the Extension manager that it's version 3.0.1 not 3.1
2) it doesn't install but returns that this extension is already installed (?)

it worked anyway. The version is installed and I can access the settings in Options again.
