### ISSUE TITLE
Improve the frame rate

### ISSUE THREAD

**Issue by HO-COOH** [lkytal/SmoothScroll#29]
It's a good plugin (I just can't understand how Visual studio Code and Jetbrians have this for years while Visual studio doesn't). Anyway, it would be so much better if you can improve the frame rate of scrolling, because it looks particularly bad on higher refresh rate monitors.

**Comment by lkytal** [comment]
Uploaded a new version that adds FPS options, just note that this is still under development, feedbacks are welcome.

**Comment by HO-COOH** [comment]
Great work. After updating the plugin, the scrolling is substantially smoother. But it didn't seems to have a difference when the `Scrolling FPS` is set to any option. I didn't feel any difference when it set to "very high" or "very low" and even "none".
Besides, I would suggest the animation ratio to be even faster to match the effect on Visual Studio Code.

**Comment by lkytal** [comment]
Uploaded version 3.2.0 which should respect FPS options now, together with some performance improvement.
