### ISSUE TITLE
VS15 update 2 - 4.6.0.1038 - Jerky not smooth

### ISSUE THREAD

**Issue by tlhintoq** [lkytal/SmoothScroll#5]
As the title says, scrolling has become jerky with latest updates from MS.
Shift-scroll (side to side) is great
Alt-scroll (page by page) is great
Using scroll bar is fine.
But just regular scroll wheel scrolling shows noticeable delay between scroll wheel and text actually scrolling... is jerky not smooth...

FYI: This is on a 3rd monitor, in portrait mode, on a C# file of 3000 lines.  
Same configuration as I've always had, but noticed the jerkiness since most recent MS KB update for VS2015update2.

**Comment by lkytal** [comment]
Which KB update exactly? I'm using vs2015up3 while this problem does not happen.

**Comment by tlhintoq** [comment]
KB3151378_23may16 

I hadn't seen that update 3 went general release two days ago.  

I'll update my PC today and report back if that resolved the issue.

On 2016-06-29 02:35, Lelouch lkytal wrote:

> Which KB update exactly? I'm using vs2015up3 while this problem does not happen. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/lkytal/SmoothScroll/issues/5#issuecomment-229268964
[2]
https://github.com/notifications/unsubscribe/AK010k4xuhlpoutYwVDe9_RXk7Euqnquks5qQhIagaJpZM4JAHzK

**Comment by lkytal** [comment]
I could not find the exact reason for this, nothing seems to be the cause of this lag.

**Comment by tlhintoq** [comment]
Thanks for looking.  Here’s what I’m seeing happening…

 

At first launch all is good.  After a few debugging sessions it starts to lag.  More sessions, more lag.

 

I am remote debugging an Android tablet over wifi.  This is a Xamarin.Forms solutions for iOS/Android/UWP.

 

I reboot at lunch since I’m stopping for a bit anyway – then all is good again.

I start noticing lag again by 2:30-ish, but not enough to stop me from working.

By 4-4:30 it would stop me, but its time for end-of-day paperwork etc.

Then I shut down for the day, giving me a fresh start the next morning.

 

Honestly, the smooth part of scrolling isn’t what I’m after. It’s the left-right scroll feature since my monitor is turned portrait.  If I could turn off the smooth and just keep the left-right I’d be happy.

 

Regards,

Clint

**Comment by lkytal** [comment]
I'll updated version 2.1.0 which enables you to turn smoothscrolling off sperately.

**Comment by tlhintoq** [comment]
Oh wow.  Thank you!
