### ISSUE TITLE
The XAML designer doesn't smooth in VS 2015 Update 3

### ISSUE THREAD

**Issue by SLAPaper** [lkytal/SmoothScroll#6]
OS Version: Windows 10 Insider Preview Build 14385
VS Version: Visual Studio 2015 Community Update 3 Ver.14.0.25422.01

The plugin works fine with text editor, but not work in XAML designer. Need I take some extra configuration or provide some more information?

Thank you.

**Comment by lkytal** [comment]
It seems like that XAML designer does not share scrolling mechanism with text editor, so it will take some time to figure out how...
