### ISSUE TITLE
Blurred Text Before Scrolling Stops

### ISSUE THREAD

**Issue by Manuzor** [lkytal/SmoothScroll#9]
When scrolling smoothly, the the font is blurred quite a bit shortly before . In fact, I was unable to perceive any scrolling movement while this was happening.

My guess is that this can be solved by clamping the scroll value after it reached a certain threshold (which might be set in the options), effectively stopping the scrolling earlier than it would have.

**Comment by lkytal** [comment]
I've noticed this isssue long ago, however, this issue seems caursed by windows text render and no decent solution now.

**Comment by hsandt** [comment]
I misposted that issue on the GitHub of the other SmoothScroll plugin by Rick Sladkey: https://github.com/ricksladkey/SmoothScroll/issues/12
... and he suggested to deactivate Graphics acceleration from Tools > Option > Environment.

It didn't work for me, only delaying blur to a bit later. But I mention it here, in case it works for other users.
